title: "Takraw's blog"
description: "blog เก็บ scripts ,, ขอกาวป๋องดิ"
locale: th
author: "Surapong Naowasate"
url: "https://hunzo.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache
markdown: kramdown
theme: null
include: ["_pages"]
