title: "ชื่อเว็บไซต์ของคุณ"
description: "คำอธิบายเว็บไซต์"
author: "ชื่อของคุณ"
locale: th
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache
markdown: kramdown
